name: Run Python Tests
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    win-build: 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install Python 3
          uses: actions/setup-python@v1
          with:
            python-version: 3.6
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run tests with pytest
          run: pytest 
