name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  linux-build:
    runs-on: ubuntu-latest 

    steps:

      - name: Run a figures tests
        run: echo python.exe -m unittest
  win-build:
      runs-on: windows-latest 
  
      steps:
  
        - name: Run a figures tests
          run: echo python.exe -m unittest
